
resource_types:
- name: capistrano
  type: docker-image
  source:
    repository: 10.23.48.45:5000/capistrano-resource
    tag: "latest"
    insecure_registries: [ "10.23.48.45:5000" ]

resources:
- name: code-microserviceA
  type: git
  source:
    uri: https://github.com/bruzos/flight-school
    branch: master
- name: microserviceA-docker-image
  type: docker-image
  source:
    repository: 10.23.48.45:5000/microserviceA
    tag: "latest"
    insecure_registries: [ "10.23.48.45:5000" ]
- name: stagging-deployment
  type: capistrano
  source:
    stage: staging
    private_key: {{aws_web_key}}

jobs:
- name: unit-tests
  serial: true
  plan:
  - get: code-microserviceA
    trigger: true
  - task: execute-tests
    file: code-microserviceA/build.yml
- name: update-microserviceA-docker-image
  plan:
  - get: code-microserviceA
    trigger: true
    passed:
      - unit-tests
  - put: microserviceA-docker-image
    name: update-microserviceA-docker-image
    params: {build: code-microserviceA}
    get_params: {rootfs: true}
- name: stagging-deployment
  serial: true
  plan:
  - get: code-microserviceA
    trigger: true
    passed:
      - unit-tests
  - put: stagging-deployment
    params:
      path: code-microserviceA
